# Site settings
title: Max Ukhanov's personal site.
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Maksym Ukhanov 
user_description: Interested in projects based on media processing for mobile, IoT, and embedded systems. Over 6+ years of commercial software development and 4+ years of System Administration. 
user_title: Software Developer
email: max.ukhanov@gmail.com
twitter_username: ukhanoff
github_username:  ukhanoff
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
